SET TERM ^ ;

CREATE OR ALTER PROCEDURE GET_ROLE_PERMISSIONS (
    role_id integer)
returns (
    id integer,
    permission_id integer,
    name varchar(255),
    notes blob sub_type 0 segment size 80)
as
BEGIN
  FOR SELECT R.ID, PERMISSION_ID, NAME, NOTES
  FROM ROLE_PERMISSIONS R JOIN PERMISSIONS P ON P.ID = R.PERMISSION_ID
  WHERE ROLE_ID = :ROLE_ID AND GRANT_OR_REVOKE = 'G'
  ORDER BY NAME
  INTO :ID, :PERMISSION_ID, :NAME, :NOTES
  DO
  SUSPEND;
END^

SET TERM ; ^

GRANT SELECT ON ROLE_PERMISSIONS TO PROCEDURE GET_ROLE_PERMISSIONS;

GRANT SELECT ON PERMISSIONS TO PROCEDURE GET_ROLE_PERMISSIONS;

GRANT EXECUTE ON PROCEDURE GET_ROLE_PERMISSIONS TO SYSDBA;